# Generated by Django 2.2.5 on 2019-12-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jours',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
