# Generated by Django 2.2.5 on 2020-01-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanapp', '0003_auto_20200103_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='jour',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
